apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: plex-sopssecret
    namespace: plex
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: truenas-smb-secret
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            username: ENC[AES256_GCM,data:KAp3JU9mYw==,iv:xPp+Z+xbM+xmmHUX/njOsmgtC05E+uqOqDPEhImA+CA=,tag:st5h6on7FFpncppXQVWdCA==,type:str]
            password: ENC[AES256_GCM,data:JYGAXfvglnW3h2p4HhM=,iv:8BqevwtLIlNhR3353oGDD8AMReDykZzeim1HAynEsEU=,tag:auaHELd+ldW5CXQrEVeIVw==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dkFreG92NXRvQWg0em5R
            UEE5cGVwMU1jaWtvVGM3SERLOFRpTWJPNVdBCjVzQTh6MXBTYmJGenFRMlF3UHp0
            d09xclVrSlBhRmFiYkJVSUVLbWk4LzAKLS0tIGdZbUZVL0ZvRlVSdmd3eXVoYm1J
            TlpTN3FLTm0ranQvaG1PTTM1YkdGRDgKY4gBQD0+kE91eJ4Ks0sXuTVg999mJSdQ
            uSFsJmEPVFQ+rQ6oENEGnDRgPNd+tx296Xio/Kszu2jFHae9UKPEjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b0pOYm9pNXpNY1loVXVO
            eEdtRVRoRzFwZ0pwMkllV0w2a1RNU2JLT0JnCmUralhTS2VMYVpLT0VoQlJkc0lx
            ck1FelVsMlVlTlFxZ2NsRGlBNjdYdWMKLS0tIGthVE12Z2xNaWpCdGF2NTQ3QkNK
            TGYrUkZDL3RzUk5IcG1XUWZWdy9iSm8K1aYLzGIcOB0/R88BoPu0jPVllA9VsjIF
            TFjbpngAPIbXabFvr9vMLBzpVa4cs6ZViM2CWGpbffUbH8xYvix6Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T05:48:57Z"
    mac: ENC[AES256_GCM,data:+DfbJc8wCLddPDHzky1dIprrb1XUsI1RqfNcI1LK/9WzjcRxjcwPFqO7sZPy9JhEm12qW2557Rl6kXbLhqQWBMwUxnnpGv0fSJDoEBSzHzuOswgNzlitLQTb7QSOpH6tjTxkoM1XOCJLzfTY1wvVH5KUPOtvYgtLVzPdXTFWA9U=,iv:1fBTeXzYGSIdn23AltWYd3zftt7LV9Uf8Dg/kzUibZU=,tag:Sa5L5FEaW44siFdvLotffg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
