apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: unifi-mongodb-sopssecret
    namespace: unifi
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: unifi-mongodb-secret
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            mongo-root-username: ENC[AES256_GCM,data:pvbfiZA=,iv:V0Rl69dU0/WUU017mXnSq9EFS2zMIwfMonDa/98kBoo=,tag:Gyj4cFw7J6h/EfTAM3VLhA==,type:str]
            mongo-root-password: ENC[AES256_GCM,data:0+1ZBe92pxxA4n0j+Q==,iv:k4wHT/ywuegz7Ww71PNqQRM2H3CVf/mfZjwrz4HjfYE=,tag:Ei1KgY6rvKV6DTYADnBFmQ==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDemE5dGpJcnEwSFo1UlB5
            MmVNYkxPV21xeFRkSGE4ZExnWi9uZk9kYndnCmY0amlVWmhGWG1FeEE4bTYwb2Qw
            TDU5U3NHaDF1bFZCUHZhSlBCa1RmZ00KLS0tIFFmQ0ZxNFNveWdBS1RQUUVDV1hR
            S2txZkE5bVVtR1dEcGpxS250eE9DZ2cKcP1xOKcCsH4yq1GApGmAM2pXP3xAcjVJ
            5Rw5LeAVmdZjtzOdLlBHpuqlWACMHnJYOYO14maZLQO+dk9wrVrlzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR2NpamJQb3pPVXYrdDVU
            RVNiLytIaTJPNG1HWGM0MVdJVEVoTVdPN21FCkR4NTl5bk1COC9WUW9BR2lUU0d6
            dFRXVm1GcnJTTEJoZlpMOXJ2bnc2SjQKLS0tIEhYSGdDZEFvc1dXSFFIR2I2SW8z
            SU5rdDhNS0s3UU1PVVR4TUVpNVlCWVUKsxaiO3MolfYMjF0zxVk47kLd8a/ShvZn
            j2d4jzA1IcqhGUtc270+O7Ex+qKp6KBBC8T36vpmE0/DYb7PloLx8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T01:40:00Z"
    mac: ENC[AES256_GCM,data:KKSCfITZA/TIl1a+RoLER9QBxPFWtaYD3K3FM+LUhl6cTF7GNn8BXatl45HxHbP3LD9cOuByVzFI3CvsGPW441pbygoEBxzlFFRj9jw+oaWbNzyv6hoGIy4+XZRUOVAzg5qF3ejAXmqzb9CQUh5PJuP81uWdRsI2KLlVUOaPMAg=,iv:8/Voe/pS7gXX+yqunl7DRsy58qiECt2U2eBeTkCEVUw=,tag:+81xErAzfJ63L/HDXu7icA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
