apiVersion: v1
kind: Service
metadata:
  name: qwen-vl
  namespace: qwen-vl
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  selector:
    app: qwen-vl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
