apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-sopssecret
    namespace: prometheus
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: alertmanager-alertmanager
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            alertmanager.yaml: ENC[AES256_GCM,data:gC7pFhtRykXkPYl3AhooT83IWlDRP2kGW8CPWjrlYP5Vg9/pEjQmFDolTIOG1kVf0kpfmqQ7GpFVuNVA8oGtG/z6ZtAwrm76cknwaYA6zylDBZmo++kkP44h1xxjf/WOpzX+mMOCMPpIc2aKdKpKrJnuBMc2mNuIw3eha49OKkgkF0GMej1GRqwgHNQWE6fMLCT6xaL5oaAF/DVamBaIZIL8ymUU9gymwK+lpUQ1S2FU4ufyHrHQlZz3KC4O/iByshJEwG148N9iBhMgzjVj042rqb/cEnXHkjzZ89b+8ap3PJiggbQAVyu27h7JNkrPXC3khDmt5btupbAcRwIM/WUsT7+glB+3gLUGvG/mW6AMfmZRGpsBum1snHlj1k083m8OGSOnOC+pqlRNCGA9T1tbKlGNShOJNoXOI9xPhUdxRkOwQjqvjRjgzBuTDmvlte/7lNDSSdsyYsVl6DlsYZBsjnDsfV3UeiS77vHyUqj2/mxtwXGEjxB3uVPFteAfa2MN66f0tiZEzIThBBUUUBheiU51vp5lPzgvmy95tRfCpeJ4KtgEgWIPRiQS4P5O7mpvExVYsuzlL25YGu8pnZAORqGkYwZ5SbA+kLgrtxuUiNAmoMMgLWWlinS0SuqQtTR6G9gUckg7WgGl7G2VSX6TTWe92gpuWpYn+b365WU6pSiQE7Ix1q26LyD1WFIV/UoMfC0WuI7PsT7PFLsOXqH1dRte/ZyDZFC+GrlKeFBPscJpcGQiEpE7SSjk1TQBLU4CblT+0PjW4aWlrjajJC0lYwG3M31TtXoXla0gRowY7Qc0H7I4PtS34S6KqlNx7oBkvj9YuEcLjLz4baBn/S4s4BkzeEoA6/+XFgptcj5XyHp4mF6I/wDa6PSVWlRwU49ux16kx8e3wECEDPWa2CWQWvbhRV9RhkcUf8Ok44ib9OeqdcvMTAfufiVlp0WuE4FFg2mqUO4s9gaWzwMhCWEc4nUgQLK4eoBsLo0QFQF4DEcSMJ01+zVtO75KMe7Qpyu3S2dm4WFVE2oN7YBJ8m7ChBJ/yJBZ697Oo0hyq9Erv8sB+jHzkuBOnbV7CzzPcMkmQvCw20qK1ZH9FYD+8r7qJWx9juWrq4ddGqxMz7BmJV8G2ycFJ+CEYfiBRPSjSPL2xuroQUfHwALBY5IUpf5RcGbLnyPX2TqD5zA3c1v+jwn7VZHLLZeKGPwCzHYWbjhiWiLsqFxPmw==,iv:b4UTQYv/R7Lr/PIbfimgTA1zTYmvhRkMkrG2mve3T3s=,tag:kNy0TLK6YNaMRe2G/mFNaA==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc2VYbnEwK1FMeVdJTk5v
            TkxQcDVMdVB3TFZXekdNM0RrbVJKa2xVNUYwCktYUHNaV0RkMWd3WW1yM1JMcERo
            Z0kveE1FcEdvYWlMayt6ZjRkbGJzSUUKLS0tIGdEbk4zcTFtZjdOZURJNS8vL0x4
            V0RwcHZMTElBL0hpOGNjS1NadzQ2QjQK53/sZRk+qE6VTenKJuL6Lp7kCFAsMTkE
            tOsQtTkto6tM3Y5yJWee8eTmzbiBR/N8KQIT7lkxgkATmUgSIhnnVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Wm82Q215Z2xWOG1VczdD
            Y21WdmFYVVF1eGVZV1h4RDV1KzRiTGViQW1nCjlnSmU2QXVzYlBxbGUrU2RUK1N4
            YVRkUW9IY0pDYUZMWS9tbURvK1BMaWMKLS0tIEd5cUdMQU9EL08xc1N4R0F6Vm16
            QnRHSWI3eksvN0NhQzRLcG42WEhyTEUKKF9D2bQH0ni7WoeA2m2MzQmijtDI7Af8
            ZUnc7uIt77wHtkuOXFppiRX7qfgYY4m4EtO51CQYW7bKPEo1b4XmnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:23:01Z"
    mac: ENC[AES256_GCM,data:gk0GmiTlEvaVXPIAjs8ZPoOzX01hw4YzZ2Ve/iuFn/rZxLuh1Ew2nqvJh+eBdpCuua6xHgo02FMsycSDdCbtwafHBT+Q0WqEf+3sKGqIpJgI2aT/CMPzxgxYu0s76121Xb5/S7Sgf7F9H8GDbDi0RS/g0WmpPrbS3FbGRDXmm3g=,iv:tU4op+HbaUDoRBMDswX3vFDcs/4zbnyV6VPUWoAi244=,tag:230ghhGHKTmP9xhs26pt+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
