apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-sopssecret
    namespace: prometheus
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: alertmanager-alertmanager
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            alertmanager.yaml: ENC[AES256_GCM,data:s5VQkQsuz6IpIIv+w7oinLtwYxdMaX9EhxCtxejvsPbEcMiIkHRpFaNl/En5WPPrr3v9hWE+1rmpSBQ8ai+Z2CQZ3g3LqZF/SQEuWyW5FInkE+l2hM93mHEztal0e97WDnRUEHmQg3VqelQXDwCyUhW34ohDe77zQaOh91V/T6CePk+7u+LHWeMP2cmwLSpKInZYQ5PbVKa2FNbt4X4pmUa+wSHtHhL/QDmtdzBe53Zssq5tQbdqq2THu7s+M9TaX7Rx4cfTIfPCgyM+qJj42NscqrqQ4b3g8Y8J7piLTmwGMsPcgsqv1sYfIvPmtkNxvw6TIeYvlSw5BFGQFlZXFUFQgyu5X0hLTUARjM2CYiIHREpXvWAfz4zlct2d+FUsRZ7znN42ATiwDsuYP/VgDDUE9A9L/G9EjFHjH5EZcvBa7b/Nbyv04KKH0h9VgjFW53T/y2DRn+b7lHO7QpDtBjCaE3KG/mQBRvE223XCr+yEtvccS1cYOWjDzpb/ssYvugdM3U/2zuyztlta2afpAUORJVFtDtpESE5fpn93StRGiqUDuYJSa3QMM0cBk4gpT/m+X3TLG+0xz3IBGmoZKg5mlYlDrd424p5nOpCTb9bES4AsjfEyobE5KZCjbMHbkzbJO6p/TU1GdXROqktAGhkwtMnxbyuZ/1XjwSGl8XRZzJjV4vP4jz0TfkPxwF2c+rx9BcfmYY5Irvi8mT36E5EaABWhhvKzQszZRB3TWbFjWfhb4S+8NEfxXfL6DBPqodWrfF26zJkvloa3Q0ggW00YwPU=,iv:oizXWL+ivOtjo+qvmBVac3jZA3o5kaDSi5iNvifJ/gM=,tag:RWVIg1ma8v25iwf4A2hN1w==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSnF2c2dPdUdnMlFIenpD
            WUJITTNRUkt3MTQwclVrVy9EZWpyOHRVc2hJCkc1eDBaNGxXTE0vTFNwUXR2QjNX
            Z2xEbzN4NDJmeHdSM3RMcHhsdGdLRXMKLS0tIGk2SS93R3prM05YRmJDcVN5YWds
            SzhWbjZwdWJ3SkkxZnR1a2RnU2hCNm8KomvcxtT+Ai3xNz/XEoClfNIRmYRntdJS
            qp9eMoXkugOvKUYtaQ2wZ0+186TUzetEFmEcN4gBnuVGf/TVU5qZqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeTdHOTRqL05XZFdDU3NM
            NVk0Z3N3aW9vcXBKckh0RGtzVVdSdk84NDFFClYyRUpySm5yM1E0LzFBMkNaK2J5
            blo3UUNxdTJrM2RVVS9LTGJYeDViQUUKLS0tIEREUmU0V0VidVcvQzhBWWlMeHhn
            UkdMTzBkNiswWjY0MjdZazJtMUV5UnMKl2L4vAI0WlffoTyIFzZ8akJ9XSp97Zyw
            S5tI8bHIQQo+RP4cSJFtofi+BP6TCBANzorZFZn0nog+lMWkfmBkrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T02:27:26Z"
    mac: ENC[AES256_GCM,data:SvaCoVyZ0sys+HdvDUK4k7KNNYgJwxvbofrWTtgLQ7pAx3hh2jvF+Vh/em56xwKqs/MWFZdjuEeRag3uJCf6PFD0OvYSnf3QrVz9yOxvwrIX/LLd2cqFtVGtTYKIMYohEWg9M0OVNfHRr6A1H73lUGP7WUgHwQLZ63AWZEDA76E=,iv:PzQ9Fn/DP8MNeh0YCXsLtZpwJwL/MFN5oBFph/vvwTs=,tag:2JnT5NXWcsll5U/yOA8aAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
