apiVersion: v1
kind: Service
metadata:
  name: pocket-tts
  namespace: pocket-tts
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  selector:
    app: pocket-tts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
