apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: longhorn-aws-sopssecret
    namespace: longhorn-system
    labels:
        app.kubernetes.io/managed-by: ngarvey-homelab
spec:
    secretTemplates:
        - name: longhorn-aws-secret
          type: Opaque
          labels:
            app.kubernetes.io/managed-by: ngarvey-homelab
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:x5/Xj4Ia2oA=,iv:8Xw0mbDXGUsmOzl8NL0b88pEdQtQXyEgKLG9R1p1clw=,tag:b0JbpgTwF3Qhx5lK2Dpodg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4RnTfSuqw22skjCwios=,iv:sFRExlL6dYqkv/cT4hSIwGlfRWDcyjdrHtI0sfHzrKE=,tag:RPcVsCy79/HKjb1jAacsew==,type:str]
            AWS_ENDPOINTS: ENC[AES256_GCM,data:K2gN5ckGbtVOCX4MzrDStbykj5k8a0GQ8oHm2JMT,iv:ovE5XfCJEPOE4iQSLwyN3GpEzw87MarHDuQ1YklTzj8=,tag:OOWRzKFHLmMsGhxAu0hWaQ==,type:str]
            AWS_CERT: ENC[AES256_GCM,data:HAa2cX+7VTs2TPHO0pf0pLVQlR1kbb2ba9xeu1BeHG1lOvvG5MgHl2vzmewG+VttsXsj1khExWiuTobrAEFxlA0FE/LWEO18/SzxEfKr7HFi+oFU5FeZC292O9IArQiKvLJpBtSxgA5n/aqHeismmj0/NrBUN/ltBZ/BNPIUaT9Z1NvwwDjDIpx5iJgk8nxGzr36SDD/MYe1c4UsGJ5gaVMdkUB/lXzCjHPNwyUwnbIlTIxkhZY6MISjiTzi6kVOMNMu4CYY+sRu9vN0S+DR+CLzW072anF7fqMtXy+T/UL+JNOvqdyiq227YHg4LSJTjW1vYTogIk58YIYJPZmWiHscMSs8kfXDPHa2T0UZXFN18+kYqze8joLKfqODuC3H4IT2Q/7Jiy/we7jjNLSqdnL9Yc+bMT8vHdJyCREl2WJL/VnxH4IjzPJySXZ4p2G70q3rqrrpES0lpLcQxbntApppkNknXEadpPFep4MFBFinGZoKyZywzAcpAWLA1xCtC+xmZTb5oHw85CLVmEnIruGF21Qm65BaP86qbP4aS2HULbNbFdFTp5YnrsctdUGxV9A4iX8b08lNSsYOAxIOTQb2GsRgBbZks6gBm4Lk42p0wRMZISyGyBPXciDsXwdtwone7rHiM/40+FygQEavtEHjiREmjA6YQjq1qTkyJG7VN493Mamh5mO/DbZv8d1JkxQB3JkuqlO3RaPQ+I552nAKZU3nDtpc6Q0TJht9jkBP+7PALN4ONWeW82m17MBQ/0O0gH2q3rlLHxw8BQuLWP57kNZFRLa8FB94seacMNOCTrYJ7ke9RTzFW640QL5/qIpvY9aKZtJTCb0GpjoTZiZQ60lZfyFCFyXPP/c1XhDUBsWCk4HGWmy6Ix5gnco90ms6JqWf1oS7TNljxk1AsGWfZYQvCEd6XXMgwDCgX9eSp3rw5xTKKgt7dN8dmautjFVugqKImSiP1YULtgJPMJL2ZLCgMmmrNM8iiggF9jKNImt65L/MBuKlYWEb54d2NCFTPADBPkl3tYx2dv8yB/L31AdF7kMClNHPRLVtVNqy05zfW9cPKAWLb4cTIFwwhcdEH+pvDnWODls97zpZmDpSlztCz7CQbSbcufcnFhC6c0FWUKIEV7uEhDBCpL5fIuNNPJLIKj1gQ0KREDcjUeV4eRD8fQPdUxxTq+uztkEpjCCl2eTgC8guutpiU+ufMDO78gDcbtzPStdyeeAtMGsZf2H/r166trfk8xvY7i9J9C6kfe0CyZfkPqsF14j8xdEVjtt/M5o2axB5Kzi3n9IVAS9EK3J0B6UdGyA0K5khEQogm/RBh9fQsX/P6QccRC9bhfeI86P29b8wtFxKpPTrVW7skC067O5Bi1m1a00hgyqxyp93bbg3oC/YMt0cCqgV7cpzTrWgH/W7lXDi96FIrix5QJ4WAnuX+I8QQLVhK2kTzAJUPG99B6IZ51HrBcXblLweSSPRWkanh94IxKzmTH9fF6Ka59OZhL1knf2Ss9zMNXbTDyB/3txInagZxyEkHzOUKcx/rsfJc1EKSyzftnG8Bpa9h0SwoD0LWnWcg7v61tf+6Bw6ewsf4lRq/PnVqBrhYjz60vGlPLydwhNdXP8yv3+C8IiJyHeL1m+/vLLZPXJ/QrvghQQt0uJLJbuW6/RJgwwLvNk9qVu5o/+pECR6AcbEQhy9efXQATP9AMCZQCVYZFscugya+WQ+wR0e3guqhtAcXXhZ6Po8xOWbanYljxatODwfGP10/d0C4OjhCw==,iv:eIgYv6qp05zeCeuXfI8HCmGYtmheC4wYQXnjHFtVdRY=,tag:hT0o+kZtuvMaNgrsYUOO9g==,type:str]
sops:
    age:
        - recipient: age1nyxjtps38j4p52nmwtf96h7d9mege90ftf4xcpxppctcwq5huqys4hy5k0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOGVJWUF6SHdqNEpKb3lX
            VFNYbXpERUo5WXdmMGR5V2hJcUZ4b3E3aVZ3ClZJZE1Pd2pOZ080NWl6aTN1d3Mz
            YjV4cmR4Vi84ME9PVk0xNVF6MjRlNWsKLS0tIDJzZ3VhSUtFdC9mRWZxOTVOc2o2
            YUFoV1hNcHl1eFR5aFBHeWxqQ1U1eEkKGO56tVK9dcciTyPlK4p5QDs/jr46i/Jl
            /c9xTOWIjAyrbLX44+K0fqyiiUAqjxL3JON0VsFkndpXrZyKoyjFmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zd28lg5yxxc06jnyym92fep4gdwwnk3k3my9l247pvskjdj8mv4sa89d08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVDMrWllTMTNOV2dNZUVU
            QkFTdFB0MWdVNkpRRjZvM0FPalBIZi9TSjJJCkwyend0eVNmNmpxdmdYaGQvVTdF
            R0JieXdNU3NEU3lqTWxLZDRNRWFURWsKLS0tIGhyMStDSmR6bDBjY1RXS1ZXZi9s
            YjAyUHlOS3M4TnF4eGpPUFFVRDFlRWcKZHypyD5XrTADWfjwSqePyc+KlETGvOaz
            +ZoEH+jTIYNf/fm7vWj3/3EWfrCRRDJYdwD72MgCruYk3jnSv+xPGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T18:04:36Z"
    mac: ENC[AES256_GCM,data:shBLaR9RqJeTKwPD9C3xNWRraiiWXyVMlHaF/sNCUYf2SmpOHkoKr+/q7QfI8XwYdHufZdnTr5tRiS22LunipUMDb5ZJVKD44gu4Gtjhh/Vc5gEIYiQ+287eI12zdQOGiCD6/aJDf/i2zHhbSB2aeHU9dfLQQu16M8iawA+YyGc=,iv:UYV6N8ZfK7lq2a9xFNlwsPoXo/A6Cs3GAXebDdybxUU=,tag:QcPzLSSuBczWf+FUDnXIhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
