apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-wffc
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  # Automatically applies the "all-volumes" recurring job group to all PVCs using this StorageClass
  recurringJobSelector: '[{"name":"all-volumes","isGroup":true}]'
