apiVersion: v1
kind: Service
metadata:
  name: zot
  namespace: zot
  labels:
    app.kubernetes.io/managed-by: ngarvey-homelab
spec:
  selector:
    app: zot
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
  type: LoadBalancer
  # Fixed IP so k3s nodes can have a stable registry address
  loadBalancerIP: 10.28.15.206
